layout_spectrum: 0.4366355643142015
typography_spectrum: 0.6194818238727748
color:
  brandStrength: 0.2781518017873168
  lightness: 0.9842740497551858
  saturation: 0.4319495796225965
  rhythmicContrast: 0.2535796349402517
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: testingsitev2
